# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

post_install do |installer|
  # 需要指定编译版本的第三方的名称
  myTargets = ['SnapKit']
  
  installer.pods_project.targets.each do |target|
    if myTargets.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end

use_frameworks!

target 'CustomFont' do
#use_frameworks!
    pod 'SnapKit'
end
